### PR TITLE
noise control

### PR DESCRIPTION
**Pull request by kotp**
Some formatting and cleanup:

- Remove trailing white space
- YAML style indentation

### CODE REVIEW

**Review by ericmenagatti — APPROVED** [review]

**Review by agustingabiola — APPROVED** [review]

**Comment by LeonardEuler** [comment]
Postman creates this file, but apparently is either not careful about ensuring that it follows RFC or something else is introducing removing trailing EOL as well as inserting trailing white space.

**Comment by kotp** [comment]
It very well could be that this is closed and not merged in, and the fix is something that should be done upstream instead, to stop the noise from happening in the first place.

**Comment by tebayoso** [comment]
No, it was closed by error and now it has conflicts. 

Jorge de los Santos

**Comment by kotp** [comment]
On 22/01/04 12:13PM, Jorge de los Santos wrote:
> > El 4 ene 2022, a las 20:51, Victor Goff ***@***.***> escribió:
> > 
> > ﻿
> > It very well could be that this is closed and not merged in, and the
> > fix is something that should be done upstream instead, to stop the
> > noise from happening in the first place.
> >
> No, it was closed by error and now it has conflicts.

The conflicts should not exist.  Check that you have up to date
information locally.

**Pull request merged**
